### ISSUE TITLE
demo无法使用

### ISSUE THREAD

**Issue by pinguo-wangchuan** [pinguo/php-msf-demo#10]
这个demo直接git下来build无法使用, 只能把代码拷贝到php-msf下面去测试。server.php代码是windows换行符，执行会报错:
[worker@newdev php-msf-demo]$ ./server.php 
-bash: ./server.php: /home/worker/php/bin/php^M: bad interpreter: No such file or directory

改为unix换行符，执行没有报错，但无任何反应，启动失败。
[worker@newdev php-msf-demo]$ ./server.php 
[worker@newdev php-msf-demo]$

**Comment by viaweb3** [comment]
目测第一个问题是由于编辑器设置的换行符不正确，导致代码被编辑器修改了，请先把编辑器的`code style`修改成 `Unix \n`，然后使用`git reset --hard`恢复原始代码。

第二个问题目测是没有执行`composer install`，可以使用`logp`命令查看错误。

**Comment by pinguo-wangchuan** [comment]
不是由于编辑器换行符不正确，而是由于windows下docker，clone出来的代码自动转换了换行符.
解决办法：
git config --global core.autocrlf input
