### ISSUE TITLE
使用registry.cn-hangzhou.aliyuncs.com/pinguo-ops/php-msf-docker:latest镜像无法使用

### ISSUE THREAD

**Issue by baykier** [pinguo/php-msf-demo#19]
操作步骤如下：
1. `git clone git@github.com:pinguo/php-msf-demo.git && cd php-msf-demo` 

此时目录为
![qq 20170929181203](https://user-images.githubusercontent.com/12169649/31011680-c4356206-a541-11e7-84a2-bca43164f2f9.png)

2.  继续 `sudo docker run -d  --name php-msf -p 8808:8000 -p 2202:22 -v $(pwd):"/home/worker/data/www" registry.cn-hangzhou.aliyuncs.com/pinguo-ops/php-msf-docker`
此时返回
![qq 20170929181306](https://user-images.githubusercontent.com/12169649/31011722-e99f138e-a541-11e7-98a4-6c6be9262db2.png)

3.  登陆容器sshd ` ssh -p 2202 worker@127.0.0.1` 执行composer install 和 supervisorctl update status如下:
![qq 20170929181553](https://user-images.githubusercontent.com/12169649/31011961-b0743ebc-a542-11e7-8a1c-0b5d4aa8b811.png)

请问docker上面提供的image不能直接用吗，需要先运行项目根目录下的*build.sh*才行

**Comment by baykier** [comment]
退出 supervisorctl 直接执行 php server.php start 就可以了 - - ！
![qq 20170929182510](https://user-images.githubusercontent.com/12169649/31012306-ea7a3390-a543-11e7-8aff-9a885674f1e1.png)

访问主页正常显示 ，汗！
![qq 20170929182822](https://user-images.githubusercontent.com/12169649/31012343-0a018c22-a544-11e7-9ce3-7d2b8e93c4c6.png)

**Comment by shellvon** [comment]
@baykier 感谢如此详细的描述
在supervisorctl中显示的错误看起来应该是由于你本地git的配置设置导致拉取的代码换行符LF被切换为Windows下CRLF导致失败，关于Git 换行符的问题你可以参见:https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

修复方式较多,您可以使用vim server.php然后执行`set filemode=unix`即可。
当然，您也可以参见之前关于这方面的问题解决方式 #10

**Comment by baykier** [comment]
@shellvon 非常感谢回复
我试过了，不是git LF替换为CRLF导致的，我所有的git操作是在ubuntu虚拟机里面操作的，所以不存在你说的那个问题，应该是[supervisor的一个bug](https://github.com/Supervisor/supervisor/issues/212)
![qq 20170930164412](https://user-images.githubusercontent.com/12169649/31044271-b810bbde-a5fe-11e7-938e-918b90da8cc4.png)
